### ISSUE TITLE
deepstream.io client for Ruby

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#71]
Create a deepstream.io client for Ruby, that connects to deepstream via TCP and supports Authentication, Permissioning, Records, Events and RPCs.

**Great resources to get started:**
[Writing a deepstream client](http://deepstream.io/info/messagestructure/writing-a-client.html)
[Deepstream Messaging structure](http://deepstream.io/info/messagestructure/index.html)
[Detailed Cucumber Specs for Incoming and Outgoing messages (and associated behaviors)](http://deepstream.io/info/messagestructure/connectivity.html)
[Fully featured NodeJS Client as a reference](https://github.com/hoxton-one/deepstream.io-client-js)

**Comment by mack7121** [comment]
I'd be interested in starting on this.  I'll go through the docs.

**Comment by eksoverzero** [comment]
Found this, and this open issue, while looking for one: https://github.com/Currency-One/deepstream-ruby

**Comment by thisredone** [comment]
We wrote the [Currency-One/deepstream-ruby](https://github.com/Currency-One/deepstream-ruby) but apparently deepstream dropped the TCP API with the 2.0 release so it won't work anymore with the newest versions. We might rewrite it for the WebSockets API though.

**Comment by yasserf** [comment]
@thisredone the changes between tcp and websocket should be quite small, all protocol aspects should be 
the same.

**Comment by prometh07** [comment]
We've released a new version of https://github.com/Currency-One/deepstream-ruby compatible with new Deepstream.

**Comment by aawooo** [comment]
@WolframHempel, should this issue still be open given the gem above?

**Comment by yasserf** [comment]
Hey aawoo,

We generally have these issues open as places for discussion. Also given V4
is out they will need a bit of work (I looked at codebase, very clean so
barely any) to get it working with the binary protocol instead of the text
based messaging.

**Comment by yasserf** [comment]
Closing this issue as resources are out of date.
